config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do

  get 'login' => :new

  post 'login' => :create
  
  delete 'logout' => :destroy
end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
      get :who_bought, on: :member
    end
    
  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", "jquery.animate-colors-min" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<div id="banner">
	<%= image_tag("logo.png") %>
	<%= @page_title || "Pragmatic Bookshelf" %>
</div>

<div id="columns">
	<div id="side">
		<div id="cart">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
				<% end %>
			<% end %>
		</div>
		
		<ul>
			<li><a href="http://localhost:3000">Home</a></li>
			<li><a href="http://www....">Questions</a></li>
			<li><a href="http://www....">News</a></li>
			<li><a href="http://www....">Contact</a></li>
			<li></li>
		</ul>
			<% if session[:user_id] == nil %>
				<%= button_to 'Login', login_path, method: :get %>
			<% end %>
		
		<% if session[:user_id] %>
			<ul>
				<li><%= link_to 'Orders', orders_path %></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
		<% end %>
	</div>
	<div id="main">
		
		<%= yield %>
	
	</div>
</div>
</body>

</html>